### ISSUE TITLE
Frequently failing Rufus::Scheduler#around_trigger does not block test

### ISSUE THREAD

**Issue by dleidert** [jmettraux/rufus-scheduler#330]
We frequently see this error happening when running the tests:

```
Failures:

  1) Rufus::Scheduler#around_trigger does not block (runs in job thread)
     Failure/Error:
       expect($out.take(3)).to eq([
         "pre #{job_id1}",
         "pre #{job_id2}",
         job_id2
       ])
     
       expected: ["pre in_1637693274.4262948_0.0_6560", "pre in_1637693274.4293563_0.0_6580", "in_1637693274.4293563_0.0_6580"]
            got: ["pre in_1637693274.4293563_0.0_6580", "pre in_1637693274.4262948_0.0_6560", "in_1637693274.4293563_0.0_6580"]
     
       (compared using ==)
     # ./spec/scheduler_spec.rb:1341:in `block (3 levels) in <top (required)>'
```

**Comment by dleidert** [comment]
And there are other test issues when we build the package in our CI:

```
Failures:
  1) Rufus::Scheduler#unschedule(job_or_work_id) carefully unschedules repeat jobs
     Failure/Error: expect(counter).to eq(c)
       expected: 2
            got: 3
       (compared using ==)
     # ./spec/scheduler_spec.rb:289:in `block (3 levels) in <top (required)>'
```

<https://salsa.debian.org/ruby-team/ruby-rufus-scheduler/-/jobs/2210494>

```
Failures:
  1) Rufus::Scheduler#occurrences(time0, time1) respects :times for repeat jobs
     Failure/Error: expect(h[j0].size).to eq(6)
       expected: 6
            got: 5
       (compared using ==)
     # ./spec/scheduler_spec.rb:663:in `block (3 levels) in <top (required)>'
```

<https://salsa.debian.org/ruby-team/ruby-rufus-scheduler/-/jobs/2210495>
