### ISSUE TITLE
fix timeout issue on rubinius

### ISSUE THREAD

**Issue by jmettraux** [jmettraux/rufus-scheduler#66]
as seen in https://travis-ci.org/jmettraux/rufus-scheduler/jobs/9454076

```
Failures:
  1) Rufus::Scheduler#cron schedules
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `[]' on nil:NilClass.
     # kernel/delta/kernel.rb:81:in `[] (method_missing)'
     # ./lib/rufus/scheduler.rb:297:in `timeout_jobs'
     # kernel/bootstrap/array.rb:68:in `each'
     # ./lib/rufus/scheduler.rb:294:in `timeout_jobs'
     # ./lib/rufus/scheduler.rb:262:in `start'
     # kernel/bootstrap/proc.rb:22:in `call'
     # kernel/bootstrap/thread18.rb:54:in `__run__'
  2) Rufus::Scheduler::Job Rufus::Scheduler::RepeatJob #pause pauses the job
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `[]' on nil:NilClass.
     # kernel/delta/kernel.rb:81:in `[] (method_missing)'
     # ./lib/rufus/scheduler.rb:297:in `timeout_jobs'
     # kernel/bootstrap/array.rb:68:in `each'
     # ./lib/rufus/scheduler.rb:294:in `timeout_jobs'
     # ./lib/rufus/scheduler.rb:262:in `start'
     # kernel/bootstrap/proc.rb:22:in `call'
     # kernel/bootstrap/thread18.rb:54:in `__run__'
  3) Rufus::Scheduler#unschedule(job_or_job_id) carefully unschedules repeat jobs
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `[]' on nil:NilClass.
     # kernel/delta/kernel.rb:81:in `[] (method_missing)'
     # ./lib/rufus/scheduler.rb:297:in `timeout_jobs'
     # kernel/bootstrap/array.rb:68:in `each'
     # ./lib/rufus/scheduler.rb:294:in `timeout_jobs'
     # ./lib/rufus/scheduler.rb:262:in `start'
     # kernel/bootstrap/proc.rb:22:in `call'
     # kernel/bootstrap/thread18.rb:54:in `__run__'
```
